---

# User Variables
unixpassword: pass123

# Database Variables
db_setup: true #By default it will install MariaDB and setup it
dbname: fivem
dbuser: fivem
dbpassword: pass123

# FiveM Variables
install_directory: /opt/fivem # server will be installed in that directory
server_port: 30120
txadmin_port: 40120
server_locale: root-AQ # please DO replace root-AQ on the line ABOVE with a real language!
server_name: "Testing Server"
server_steamKey: 123456
server_licenseKey: 123456
