---
- name: Add MariaDB repository key
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc 
    state: present

- name: Add MariaDB repository
  apt_repository:
    repo: "deb [arch=amd64,arm64,ppc64el] https://mirrors.up.pt/pub/mariadb/repo/10.5/ubuntu focal main"
    state: present

- name: Install MariaDB
  apt:
    name: mariadb-server
    state: latest
    update_cache: yes

- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Add MariaDB Rule
  community.general.ufw:
    rule: allow
    port: '3306'
    proto: tcp

- name: Create DB
  community.mysql.mysql_db:
    name: "{{ dbname }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Removes all anonymous user accounts
  community.mysql.mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create User
  community.mysql.mysql_user:
    state: present
    name: "{{ dbuser }}"
    password: "{{ dbpassword }}"
    host: "%"
    priv: "{{ dbname }}.*:ALL"
    login_unix_socket: /run/mysqld/mysqld.sock
