---
- name: Update apt repo and cache
  apt: 
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt: 
    upgrade: dist 
    force_apt_get: yes

- name: Install needed packages
  apt:
    name: ['git', 'ufw', 'wget', 'python3-pymysql']
    state: latest

- name: Start UFW
  community.general.ufw:
    state: enabled

- name: Deny Incoming by Default
  community.general.ufw:
    default: deny
    direction: incoming

- name: Allow Outgoing by Default
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Permit SSH with rate limit
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Create fivem user
  user:
    name: fivem
    password: "{{ unixpassword|password_hash('sha512') }}"
    update_password: on_create

- name: Add SFTP config to the SSH file
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match User fivem
      ChrootDirectory /home/%u
      ForceCommand internal-sftp 

- name: Restart SSH service
  service:
    name: ssh
    state: restarted