---

- name: Create artifacts folder
  file:
    path: "{{ install_directory }}/artifacts/"
    state: directory

- name: Extract artifacts
  unarchive:
    src: https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/3383-913a4441508dcb562337a67c0c727ea11f6cbe39/fx.tar.xz
    dest: "{{ install_directory }}/artifacts/"
    remote_src: yes

- name: Download resources folder
  git:
    repo: 'https://github.com/citizenfx/cfx-server-data.git'
    dest: "{{ install_directory }}/data/"

- name: Create FiveM config file
  template:
    src: server.cfg.j2
    dest: "{{ install_directory }}/data/server.cfg"

- name: Create FiveM service
  template:
    src: fivem.service.j2
    dest: /etc/systemd/system/fivem.service

- name: Fix permissions on the server
  file:
    path: "{{ install_directory }}"
    state: directory
    recurse: yes
    owner: fivem
    group: fivem
    follow: no

- name: Make folder owned by root
  file:
    path: "{{ install_directory }}"
    state: directory
    owner: root
    group: root
    follow: no

- name: Reload systemctl configs
  systemd:
    daemon_reload: yes

- name: Enable and start FiveM service
  service:
    name: fivem
    enabled: yes
    state: started

- name: Allow connection to txAdmin
  community.general.ufw:
    rule: allow
    port: "{{ txadmin_port | string }}"
    proto: tcp

- name: Allow connection to FiveM Server
  community.general.ufw:
    rule: allow
    port: "{{ server_port | string }}"
