---

- name: Create artifacts folder
  file:
    path: /home/fivem/artifacts/
    state: directory

- name: Extract artifacts
  unarchive:
    src: https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/3383-913a4441508dcb562337a67c0c727ea11f6cbe39/fx.tar.xz
    dest: /home/fivem/artifacts/
    remote_src: yes

- name: Download resources folder
  git:
    repo: 'https://github.com/citizenfx/cfx-server-data.git'
    dest: /home/fivem/data/

- name: Create FiveM config file
  template:
    src: server.cfg.j2
    dest: /home/fivem/data/server.cfg

- name: Create FiveM service
  template:
    src: fivem.service.j2
    dest: /etc/systemd/system/fivem.service

- name: Fix permissions on the server
  file:
    path: /home/fivem/
    state: directory
    recurse: yes
    owner: fivem
    group: fivem
    follow: no
